In [1]:
pip install lightgbm

   ---------------------------------------- 1.5/1.5 MB 831.2 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [15]:
#Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
#Data

dataset = pd.read_csv("sc_data.csv")

dataset.head()

Product type   SKU      Price  Availability  Number of products sold  \
0     haircare  SKU0  69.808006            55                      802   
1     skincare  SKU1  14.843523            95                      736   
2     haircare  SKU2  11.319683            34                        8   
3     skincare  SKU3  61.163343            68                       83   
4     skincare  SKU4   4.805496            26                      871   

   Revenue generated Customer demographics  Stock levels  Lead times  \
0        8661.996792            Non-binary            58           7   
1        7460.900065                Female            53          30   
2        9577.749626               Unknown             1          10   
3        7766.836426            Non-binary            23          13   
4        2686.505152            Non-binary             5           3   

   Order quantities  ...  Location Lead time  Production volumes  \
0                96  ...    Mumbai        29                 215   
1                37  ...    Mumbai        23                 517   
2                88  ...    Mumbai        12                 971   
3                59  ...   Kolkata        24                 937   
4                56  ...     Delhi         5                 414   

  Manufacturing lead time Manufacturing costs  Inspection results  \
0                      29           46.279879             Pending   
1                      30           33.616769             Pending   
2                      27           30.688019             Pending   
3                      18           35.624741                Fail   
4                       3           92.065161                Fail   

   Defect rates  Transportation modes   Routes       Costs  
0      0.226410                  Road  Route B  187.752075  
1      4.854068                  Road  Route B  503.065579  
2      4.580593                   Air  Route C  141.920282  
3      4.746649                  Rail  Route A  254.776159  
4      3.145580                   Air  Route A  923.440632  

[5 rows x 24 columns]

In [17]:
# Data Split

feature = ['Price', 'Availability', 'Stock levels', 'Lead times', 'Order quantities']

target = ['Number of products sold']

X = dataset[feature]
y = dataset[target]


In [18]:
# train_test_split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)


In [19]:
# regression models

import lightgbm as gbm

In [20]:
train_data = gbm.Dataset(X_train, label = y_train)

In [21]:
params = {
    'objective': 'regression',
    'boosting_type': 'gbdt',
    'metric':'mse',
    'num_leaves': 31,
    'learning_rate': 0.05,
    'feature_fraction':0.9
}

In [14]:
num_round = 100

In [23]:
best = gbm.train(params, train_data, num_round)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000171 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 124
[LightGBM] [Info] Number of data points in the train set: 80, number of used features: 5
[LightGBM] [Info] Start training from score 453.200000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gai

In [28]:
y_pred_gbm = best.predict(X_test, num_iteration = best.best_iteration)

In [30]:
y_pred_gbm

array([602.26477999, 462.50809993, 470.25702294, 382.77090386,
       325.46704061, 413.25164768, 375.62754257, 557.18903774,
       332.66809798, 444.34647958, 346.02050077, 409.1354491 ,
       497.41937115, 360.4174601 , 336.97107195, 346.89585609,
       442.85618876, 354.04827904, 570.12310461, 269.46575199])

In [35]:
#linear regression

from sklearn.linear_model import LinearRegression

lr = LinearRegression() 

lr.fit(X_train, y_train)



LinearRegression()

In [36]:
y_pred_lr = lr.predict(X_test)

In [37]:
y_pred_lr

array([[546.80624844],
       [540.60706295],
       [487.73006047],
       [427.84249504],
       [384.22488362],
       [468.34153637],
       [456.88161439],
       [482.37112349],
       [378.46155466],
       [421.01744808],
       [387.99253363],
       [431.57917438],
       [406.11914976],
       [388.30933182],
       [429.85682584],
       [372.52635105],
       [432.66790636],
       [451.52380592],
       [461.77777664],
       [396.1535143 ]])

In [38]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor() 

rf.fit(X_train, y_train)



F:\ANACONDA\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


RandomForestRegressor()

In [39]:
y_pred_reg = rf.predict(X_test)

In [40]:
y_pred_reg

array([462.57, 747.51, 444.78, 384.63, 285.96, 427.27, 467.59, 407.37,
       418.34, 523.94, 382.75, 430.17, 377.18, 327.45, 448.1 , 411.7 ,
       526.81, 410.45, 650.38, 293.79])

In [41]:
from sklearn.ensemble import GradientBoostingRegressor

Gb = GradientBoostingRegressor()

Gb.fit(X_train,y_train)
y_pred_Gb = Gb.predict(X_test)
y_pred_Gb 

F:\ANACONDA\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([324.82963324, 714.2279852 , 428.81113464, 294.90693572,
       400.85158228, 533.48228568, 602.80082334, 397.62475838,
       375.23793316, 535.80137787, 470.89618585, 470.56853141,
       636.2629851 , 275.31514383, 484.25423431, 447.72760531,
       584.91254455, 365.32327986, 839.54765261, 241.73759352])

In [50]:
from sklearn.metrics import r2_score

r2_score(y_pred_gbm, y_test)


-13.623478495005612

In [49]:
r2_score(y_pred_lr, y_test)

-44.94155526964318

In [48]:
r2_score(y_pred_reg, y_test)

-9.770641816460195

In [47]:
r2_score(y_pred_Gb, y_test)

-4.800306363680503